# Generated by Django 3.0.5 on 2021-12-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_desc', models.CharField(max_length=50)),
                ('inc_place', models.CharField(max_length=50)),
                ('inc_date', models.CharField(max_length=100)),
            ],
        ),
    ]
